### PR TITLE
Refactore how we get matured blocks

### PR DESCRIPTION
**Pull request by noescape00**
Removed `MaturedBlockReceiver`, `RestMaturedBlockRequester`, `EventsPersister`.
Added `MaturedBlocksSyncManager`.

So before we used to have a mix of PULL and PUSH mechanism. Now there is only PULL mechanism.

The PR is not ready for a merge just yet because I need to add tests but it can already be reviewed. It already works and `CrossChainTransferStore` is advancing nicely. 

It looks like this PR already improves the syncing speed and stability by a lot. 

Please test the PR during the review- run the setup.

### CODE REVIEW

**Comment by quantumagi** [comment]
Can you explain how you are being notified of changes to avoid repeatedly polling?

**Comment by noescape00** [comment]
>the target chain cannot know about events on the source chain or when to expect them, so it feels natural to get the source chain to push those events to the target one

Yet you had logic to pull every 30 seconds anyway. If you are doing pulls in particular interval why do you need push at all? 

>there is a plan to have a federation dashboard, and it would have been nicer to be able to push updates about statuses of transactions, db, fedmembers, to it rather than asking it to poll for info from rest endpoints all the time

For the dashboard it makes sense. But It should be separated from nodes syncing between each other, they should use different API.

>but reasoning from push is easier for me when the problem is more natural from a push point of view.

Problem with pushing is that you can't handle easily situation when you are not pushing what is needed. 

So we have 2 chains and both synced till 100k. And each synced matured blocks up to 50k. Now we shut down nodes and start them. How do we know we should send from 50k? Well, now we need to save to db what was the last block height we pushed, ok. 
Now imagine one of the nodes died and had to start from scratch. How does the 2nd node know that it can't push from 50k anymore but need to start from 0 again? 
Better to let another node decide what it needs, it is much simpler and resilient.

**Comment by monsieurleberre** [comment]
> Yet you had logic to pull every 30 seconds anyway. If you are doing pulls in particular interval why do you need push at all?

There might be a few places where there is pulling, but there are also lots where there is some pushing 😂 Anyway picking one model over the other is more about picking the appropriate tool for the job than enforcing uniformity.
 
> For the dashboard it makes sense. But It should be separated from nodes syncing between each other, they should use different API.

If you are going to broadcast the information anyway, in my opinion, it is just simpler to let whoever is interested to subscribe to it, there is no real need for duplicating the work, but again no big deal.

> Problem with pushing is that you can't handle easily situation when you are not pushing what is needed [...].

So I agree the node needing a resync is the only one who knows what it needs (pull or push) but what prevents you from _pushing_ a message saying what you want and getting some information pushed back to you? just like when you communicate using your voice for instance ?

Anyway once again whatever the implementation if it works is good, but I don't think any of the 2 paradigm is inherently limited 😃

**Comment by noescape00** [comment]
>Anyway picking one model over the other is more about picking the appropriate tool for the job than enforcing uniformity.

Agreed. This should be done on case by case basis

>If you are going to broadcast the information anyway, in my opinion, it is just simpler to let whoever is interested to subscribe to it, there is no real need for duplicating the work, but again no big deal.

Imho having push and pull together is the duplication that is now fixed

>So I agree the node needing a resync is the only one who knows what it needs (pull or push) but what prevents you from pushing a message saying what you want and getting some information pushed back to you? just like when you communicate using your voice for instance ?

That complicates the design a lot if we go using those workaround. As I mentioned before if you want to use push then you need to add storing info of the last thing pushed and you need to save it to the harddrive. And now you also need additional method to push info from where other node should push. That's a lot of stuff comparing to what there is now.

**Pull request merged**
